export const dark = {
  statusBarColor: '#888888',
  background: '#181828',
  color: '#efefef',
  titleColor: '#fff',
  border: '#585858',
  buttonBackground: '#17607b',
  buttonText: '#efefef',
  headerBackground: '#0c0c12',
  sideMenuBackground: '#101020',
  sideMenuItemBackground: '#1a1a2d',
  sideMenuItemColor: '#efefef',
  iconsColor: '#efefef',
  separatorColor: '#efefef',
};
